"""empty message

Revision ID: 49d86f132e54
Revises: 2fae9bf0fcae
Create Date: 2024-12-05 07:43:06.578950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d86f132e54'
down_revision = '2fae9bf0fcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('liked_at')

    # ### end Alembic commands ###
